# Generated by Django 5.2.1 on 2025-05-24 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("lux_double", "اتاق دبل لوکس"),
                            ("suite_city", "سوییت با منظره شهر"),
                            ("single_modern", "اتاق سینگل مدرن"),
                            ("royal_king", "رویال کینگ"),
                            ("junior_suite", "جونیور سوییت"),
                            ("family_suite", "سوییت خانوادگی"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "bed_type",
                    models.CharField(default="اتاق سینگل مدرن", max_length=50),
                ),
                (
                    "size",
                    models.IntegerField(
                        blank=True, help_text="متراژ بر حسب متر مربع", null=True
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True, help_text="حداکثر تعداد نفرات", null=True
                    ),
                ),
                ("view", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price_per_night",
                    models.IntegerField(
                        blank=True, help_text="قیمت هر شب به تومان", null=True
                    ),
                ),
                ("features", models.TextField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amenities", models.ManyToManyField(blank=True, to="rooms.amenity")),
            ],
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="room_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
