# Generated by Django 5.1.6 on 2025-04-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("SGL", "SINGLE"),
                            ("DBL", "DOUBLE"),
                            ("DLX", "DELUXE"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
