# Generated by Django 5.2.1 on 2025-05-23 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="room",
            name="number",
        ),
        migrations.AddField(
            model_name="room",
            name="bed_type",
            field=models.CharField(default="اتاق سینگل مدرن", max_length=50),
        ),
        migrations.AddField(
            model_name="room",
            name="features",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="size",
            field=models.IntegerField(
                blank=True, help_text="متراژ بر حسب متر مربع", null=True
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="view",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="price_per_night",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("lux_double", "اتاق دبل لوکس"),
                    ("suite_city", "سوییت با منظره شهر"),
                    ("single_modern", "اتاق سینگل مدرن"),
                    ("royal_king", "رویال کینگ"),
                    ("junior_suite", "جونیور سوییت"),
                    ("family_suite", "سوییت خانوادگی"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="room_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
