# Generated by Django 5.2.1 on 2025-05-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_remove_room_is_available_remove_room_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="price_per_night",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
