# Generated by Django 5.1.6 on 2025-04-13 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="date_requested",
            new_name="requested_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="guest",
        ),
        migrations.RemoveField(
            model_name="service",
            name="staff",
        ),
        migrations.AddField(
            model_name="service",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("cleaning", "نظافت"),
                    ("laundry", "خشکشویی"),
                    ("maintenance", "تعمیرات"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
