# Generated by Django 5.1.6 on 2025-05-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="مدیر"),
        ),
    ]
