# Generated by Django 5.1.6 on 2025-05-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_guest_is_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="manager"),
        ),
    ]
